services:
  backend:
    build: .
    ports:
      - 3000:3000
      - 9229:9229 # for debugging
    volumes:
      - .:/app
      - /app/node_modules
      - todoist-db:/data/todoist.db
    command: pnpm start
    environment:
      ENV: "development"
      DB_FILE_NAME: "file:data/todoist.db"
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./app

volumes:
  todoist-db:
    driver: local

networks:
  default:
    driver: bridge
